// GENERATED by scripts/buildDraftPool.ts — do not edit by hand.
// The app imports the current draft pool through this module so a season
// rollover only changes generated files.
import poolJson from './draftPool.2026.json';
import type { DraftPoolFile } from '@/types/draft';
import { applyCustomRankingsToPool, getSavedCustomRankings } from '@/utils/customRankings';

const rawPool = poolJson as DraftPoolFile;

if (typeof window !== 'undefined' && window.localStorage) {
  try {
    const saved = getSavedCustomRankings();
    if (saved) {
      const { updatedPlayers } = applyCustomRankingsToPool(rawPool.players, saved);
      rawPool.players = updatedPlayers;
    }
  } catch (e) {
    console.error('Failed to load custom rankings from local storage:', e);
  }
}

export const POOL = rawPool;
